server:
  port: 20001
spring:
  application:
    name: gateway-client
  cloud:
    gateway:
      enabled: true
      routes:
      - id: path_route
        uri: lb://order-client
        predicates:
        - Path=/**
        filters:
        - name: RequestRateLimiter
          KeyResolver: userKey
          args:
            redis-rate-limiter.replenishRate: 1
            redis-rate-limiter.burstCapacity: 2
            redis-rate-limiter.requestedTokens: 1
            key-resolver: "#{@ipKeyResolver}"
  redis:
    host: 47.101.57.44
    port: 6379
    timeout: 5000

eureka:
  instance:
    instance-id: gateway-client-1
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
