server:
  port: 10020
spring:
  application:
    name: order-client
  redis:
    host: 47.101.57.44
    port: 6379
    timeout: 5000
eureka:
  instance:
    instance-id: order-client-1
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka


